apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/lib/grafana
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-storage
spec:
  volumeName: grafana-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

