apiVersion: v1
kind: Service
metadata:
  name: counter-headless-svc
spec:
  clusterIP: None # <-- Don't forget!!
  selector:
    app: counter
# not ports for this demo
# ports:
# - port: 8080
#   targetPort: 80
